version: '3.9'

services:
# MICROSERVICES
  ms-campus-kid-auth:
    container_name: ms-campus-kid-auth
    build: ./ms-campus-kid-auth
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-grades:
    container_name: ms-campus-kid-grades
    build: ./ms-campus-kid-grades
    depends_on:
      db-grade:
        condition: service_healthy
    links: 
        - db-grade
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - SECRET_KEY=1234P
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=1234
      - DB_DATABASE=db_grade
      - DB_PORT=4006
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-request:
    container_name: ms-campus-kid-request
    build: ./ms-campus-kid-request
    ports:
      - 4002:4002
    environment:
      - PORT=4002
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-schedule:
    container_name: ms-campus-kid-schedule
    build: ./ms-campus-kid-schedule
    depends_on:
      db-grade:
        condition: service_healthy
    links: 
        - db-grade
    ports:
      - 4003:4003
    environment:
      - PORT=4003
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=1234
      - DB_DATABASE=db_grade
      - DB_PORT=4006
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-school:
    container_name: ms-campus-kid-school
    build: ./ms-campus-kid-school
    depends_on:
      db-subject:
        condition: service_healthy
    links: 
        - db-subject
    ports:
      - 4004:4004
    environment:
      - PORT=4004
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=host.docker.internal
      - DB_PORT=4007
      - DB_NAME=db_subject
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-subjects:
    container_name: ms-campus-kid-subjects
    build: ./ms-campus-kid-subjects
    depends_on:
      db-subject:
        condition: service_healthy
    links: 
        - db-subject
    ports:
      - 4005:80
    environment:
      - PORT=4005
    extra_hosts:
      - "host.docker.internal:host-gateway"
# DATABASES
  db-grade:
    container_name: db-grade
    image: postgres
    ports:
      - 4006:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: db_grade
      PGPASSWORD: 1234
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-U", "root", "-d", "db_grade"]
        interval: 15s
        timeout: 10s
        retries: 10
        start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db-subject:
    container_name: db-subject
    image: mysql
    ports:
      - 4007:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_subject
      MYSQL_ROOT_HOST: '%'
    healthcheck:
        test:  ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 15s
        timeout: 10s
        retries: 10
        start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db-auth:
    container_name: db-auth
    image: mongo
    restart: always
    ports:
      - 4008:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: db_auth
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
        interval: 15s
        timeout: 10s
        retries: 10
        start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"