apiVersion: v1
kind: Service
metadata:
  name: ms-schedule
spec:
  selector:
    app: ms-schedule
  ports:
    - name: http
      port: 4003
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth
spec:
  selector:
    app: ms-auth
  ports:
    - name: http
      port: 4000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ms-subject
spec:
  selector:
    app: ms-subject
  ports:
    - name: http
      port: 4005
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ms-school
spec:
  selector:
    app: ms-school
  ports:
    - name: http
      port: 4004
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ag
spec:
  selector:
    app: ag
  ports:
    - name: http
      port: 4011
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: wa-admin
spec:
  selector:
    app: wa-admin
  ports:
    - name: http
      port: 4012
  type: LoadBalancer