// <auto-generated />
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(SubjectsContext))]
    [Migration("20221001183146_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataBase.Career", b =>
                {
                    b.Property<int>("idCareer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("idFaculty")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("idCareer");

                    b.HasIndex("idFaculty");

                    b.ToTable("Career", (string)null);
                });

            modelBuilder.Entity("DataBase.Course", b =>
                {
                    b.Property<int>("idCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("idFaculty")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("idCourse");

                    b.HasIndex("idFaculty");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.Property<int>("idFaculty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("idSite")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("idFaculty");

                    b.HasIndex("idSite");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("DataBase.Site", b =>
                {
                    b.Property<int>("idSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("idSite");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("DataBase.Career", b =>
                {
                    b.HasOne("DataBase.Faculty", "Faculty")
                        .WithMany("careers")
                        .HasForeignKey("idFaculty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DataBase.Course", b =>
                {
                    b.HasOne("DataBase.Faculty", "Faculty")
                        .WithMany("courses")
                        .HasForeignKey("idFaculty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.HasOne("DataBase.Site", "Site")
                        .WithMany("faculties")
                        .HasForeignKey("idSite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.Navigation("careers");

                    b.Navigation("courses");
                });

            modelBuilder.Entity("DataBase.Site", b =>
                {
                    b.Navigation("faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
