export enum RoleEnum {
  ADMIN = "ADMIN",
  STUDENT = "STUDENT",
  TEACHER = "TEACHER",
  EXTERNAL_CONSUMER = "EXTERNAL_CONSUMER",
  UNKNOWN = "UNKNOWN",
}

export enum StorageKeyEnum {
  AUTHENTICATION = "AUTHENTICATION",
}
